[package]
name = "oneboost-native"
version = "1.1.5"
edition = "2021"

[lib]
name = "oneboost_native"
crate-type = ["cdylib"]

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
windows-sys = { version = "0.52", features = [
  "Win32_Foundation",
  "Win32_System_LibraryLoader",
  "Win32_System_Power",
  "Win32_System_RemoteDesktop",
  "Win32_System_SystemInformation",
  "Win32_System_Threading",
  "Win32_Graphics_Gdi",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
] }
