//! Auto-update via GitHub Releases — tauri-plugin-updater.
//!
//! Mirrors the electron-updater behavior:
//!   - stable installs read `latest.json` (never see prereleases);
//!   - prerelease builds (version contains -alpha/-beta) also accept the
//!     newest stable once it passes the running version;
//!   - auto-download + install-on-quit; in-app state machine identical to
//!     shared/types.ts UpdateState.
//!
//! Release feed: every stable tag publishes `latest.json` generated by CI
//! (scripts/gen-latest-json.mjs) pointing at the NSIS `*.exe` artifact, with
//! a minisign signature produced at build time (TAURI_SIGNING_PRIVATE_KEY).

use serde::Serialize;
use std::sync::Mutex;
use tauri::AppHandle;
use tauri_plugin_updater::UpdaterExt;

const REPO_OWNER: &str = "Ahaduzzamankhan";
const REPO_NAME: &str = "1boost";

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateStatePayload {
    pub status: String,
    pub current_version: String,
    pub available_version: Option<String>,
    pub progress: Option<f64>,
    pub downloaded_bytes: Option<u64>,
    pub total_bytes: Option<u64>,
    pub error: Option<String>,
    pub checked_at: Option<u64>,
}

fn state_payload(
    status: &str,
    available: Option<String>,
    progress: Option<f64>,
    downloaded: Option<u64>,
    total: Option<u64>,
    error: Option<String>,
) -> UpdateStatePayload {
    UpdateStatePayload {
        status: status.to_string(),
        current_version: env!("CARGO_PKG_VERSION").to_string(),
        available_version: available,
        progress,
        downloaded_bytes: downloaded,
        total_bytes: total,
        error,
        checked_at: Some(crate::util::now_ms()),
    }
}

fn running_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

#[allow(dead_code)]
fn running_prerelease() -> bool {
    let v = running_version();
    v.contains("-alpha") || v.contains("-beta")
}

fn emit_state(app: &AppHandle, s: &UpdateStatePayload) {
    use tauri::Emitter;
    let _ = app.emit("oneboost://update-state", s);
}

async fn do_check(app: &AppHandle) -> UpdateStatePayload {
    if std::env::var("ONEBOOST_NO_UPDATER").as_deref() == Ok("1") {
        return state_payload("up-to-date", None, None, None, None, None);
    }
    let updater = match app.updater() {
        Ok(u) => u,
        Err(e) => return state_payload("error", None, None, None, None, Some(e.to_string())),
    };
    emit_state(app, &state_payload("checking", None, None, None, None, None));
    match updater.check().await {
        Ok(Some(mut update)) => {
            let version = update.version.clone();
            emit_state(
                app,
                &state_payload("downloading", Some(version.clone()), Some(0.0), Some(0), None, None),
            );
            let mut downloaded: u64 = 0;
            let app2 = app.clone();
            let version2 = version.clone();
            let res = update
                .download(
                    move |chunk, total| {
                        downloaded = downloaded.saturating_add(chunk as u64);
                        let pct = total
                            .map(|t| (downloaded as f64 / t as f64) * 100.0)
                            .unwrap_or(0.0);
                        emit_state(
                            &app2,
                            &state_payload(
                                "downloading",
                                Some(version2.clone()),
                                Some(pct.min(100.0)),
                                Some(downloaded),
                                total,
                                None,
                            ),
                        );
                    },
                    || {},
                )
                .await;
            match res {
                Ok(bytes) => {
                    // Cache the downloaded artifact so install_update() can
                    // install it without a second download.
                    if let Ok(mut g) = PENDING.lock() {
                        *g = Some(PendingUpdate { version: version.clone(), bytes });
                    }
                    let s = state_payload("ready", Some(version), Some(100.0), None, None, None);
                    emit_state(app, &s);
                    s
                }
                Err(e) => {
                    let s = state_payload("error", None, None, None, None, Some(e.to_string()));
                    emit_state(app, &s);
                    s
                }
            }
        }
        Ok(None) => {
            let s = state_payload("up-to-date", None, None, None, None, None);
            emit_state(app, &s);
            s
        }
        Err(e) => {
            let s = state_payload("error", None, None, None, None, Some(e.to_string()));
            emit_state(app, &s);
            s
        }
    }
}

#[derive(Clone)]
struct PendingUpdate {
    version: String,
    bytes: Vec<u8>,
}

static PENDING: Mutex<Option<PendingUpdate>> = Mutex::new(None);

pub async fn update_state(_app: &AppHandle) -> UpdateStatePayload {
    // Non-mutating snapshot: the UI polls this on load.
    state_payload("idle", None, None, None, None, None)
}

/// True when a release manifest version is newer than the running build.
#[allow(dead_code)]
fn is_newer(candidate: &str, current: &str) -> bool {
    let parse = |v: &str| -> (u64, u64, u64) {
        let core = v.split('-').next().unwrap_or("");
        let mut it = core.split('.').map(|p| p.parse::<u64>().unwrap_or(0));
        (it.next().unwrap_or(0), it.next().unwrap_or(0), it.next().unwrap_or(0))
    };
    let (a1, a2, a3) = parse(candidate);
    let (b1, b2, b3) = parse(current);
    (a1, a2, a3) > (b1, b2, b3)
}

pub async fn check_updates(app: &AppHandle) -> UpdateStatePayload {
    do_check(app).await
}

pub async fn install_update(app: &AppHandle) -> bool {
    let updater = match app.updater() {
        Ok(u) => u,
        Err(_) => return false,
    };
    // Check again so the Update object matches the live feed.
    match updater.check().await {
        Ok(Some(mut update)) => {
            let pending = PENDING.lock().ok().and_then(|g| g.clone());
            let bytes = match pending {
                Some(p) if p.version == update.version => Ok(p.bytes),
                // Background download never completed — fetch now.
                _ => update.download(|_, _| {}, || {}).await,
            };
            match bytes {
                // install() replaces the binary and relaunches (NSIS);
                // ExitRequested stops the tracker via RunEvent handling.
                Ok(b) => {
                    let _ = update.install(&b);
                    true
                }
                Err(_) => false,
            }
        }
        _ => false,
    }
}

pub fn init_background(app: AppHandle) {
    if cfg!(debug_assertions) || std::env::var("ONEBOOST_NO_UPDATER").as_deref() == Ok("1") {
        return;
    }
    std::thread::spawn(move || {
        // Small delay so first paint isn't competing with the update check.
        std::thread::sleep(std::time::Duration::from_millis(STARTUP_DELAY_MS));
        let h = app.clone();
        tauri::async_runtime::spawn(async move {
            do_check(&h).await;
        });
        loop {
            std::thread::sleep(std::time::Duration::from_millis(RECHECK_MS));
            let h = app.clone();
            tauri::async_runtime::spawn(async move {
                do_check(&h).await;
            });
        }
    });
}

const STARTUP_DELAY_MS: u64 = 15_000;
const RECHECK_MS: u64 = 6 * 60 * 60_000;

// Repo constants kept for the manifest generator + diagnostics.
pub const REPO: (&str, &str) = (REPO_OWNER, REPO_NAME);
