//! Auto-update for 1Boost.
//!
//! Two paths, in order of preference:
//!
//!   1. **Delta** — releases publish a signed `.1bdelta` patch next to the
//!      signed updater payload (see `delta` and `payload`). When the payload of
//!      the running version is in the cache, the new one is rebuilt locally and
//!      only a few kilobytes cross the network.
//!   2. **Full** — the tauri-plugin-updater path, unchanged. It is used
//!      whenever there is no cached base, no published patch, or the patch
//!      fails any verification step. This is also the only path on a fresh
//!      install, which has no payload on disk to patch against.
//!
//! Nothing about the full-update path was weakened: the plugin still verifies
//! the artifact's minisign signature itself, and the delta path adds the same
//! check plus a SHA-256 chain on top (see `delta`). Updates are staged in
//! memory and only handed to the installer once verified, so a failed update of
//! either kind leaves the current install untouched.
//!
//! Release feed: every stable tag publishes `latest.json` generated by CI
//! (scripts/gen-latest-json.mjs) pointing at the NSIS `*.exe` artifact, with a
//! minisign signature produced at build time (TAURI_SIGNING_PRIVATE_KEY).

use crate::payload;
use serde::Serialize;
use std::io::Read;
use std::io::Write;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
use tauri::{AppHandle, Manager};
use tauri_plugin_updater::UpdaterExt;

const REPO_OWNER: &str = "Ahaduzzamankhan";
const REPO_NAME: &str = "1boost";

/// Which path produced the bytes now waiting to be installed.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Mode {
    Delta,
    Full,
}

impl Mode {
    fn as_str(self) -> &'static str {
        match self {
            Mode::Delta => "delta",
            Mode::Full => "full",
        }
    }
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateStatePayload {
    pub status: String,
    pub current_version: String,
    pub available_version: Option<String>,
    pub progress: Option<f64>,
    pub downloaded_bytes: Option<u64>,
    pub total_bytes: Option<u64>,
    pub error: Option<String>,
    pub checked_at: Option<u64>,
    /// "delta" or "full": which updater path produced this update.
    pub mode: Option<String>,
}

#[allow(clippy::too_many_arguments)]
fn state_payload(
    status: &str,
    available: Option<String>,
    progress: Option<f64>,
    downloaded: Option<u64>,
    total: Option<u64>,
    error: Option<String>,
    mode: Option<Mode>,
) -> UpdateStatePayload {
    UpdateStatePayload {
        status: status.to_string(),
        current_version: env!("CARGO_PKG_VERSION").to_string(),
        available_version: available,
        progress,
        downloaded_bytes: downloaded,
        total_bytes: total,
        error,
        checked_at: Some(crate::util::now_ms()),
        mode: mode.map(Mode::as_str).map(str::to_string),
    }
}

fn running_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

#[allow(dead_code)]
fn running_prerelease() -> bool {
    let v = running_version();
    v.contains("-alpha") || v.contains("-beta")
}

fn emit_state(app: &AppHandle, s: &UpdateStatePayload) {
    use tauri::Emitter;
    let _ = app.emit("oneboost://update-state", s);
}

async fn do_check(app: &AppHandle) -> UpdateStatePayload {
    if std::env::var("ONEBOOST_NO_UPDATER").as_deref() == Ok("1") {
        return state_payload("up-to-date", None, None, None, None, None, None);
    }
    let updater = match app.updater() {
        Ok(u) => u,
        Err(e) => {
            return state_payload("error", None, None, None, None, Some(e.to_string()), None)
        }
    };
    emit_state(app, &state_payload("checking", None, None, None, None, None, None));
    match updater.check().await {
        Ok(Some(update)) => {
            let version = update.version.clone();

            // --- Delta first -------------------------------------------------
            // Every failure below is non-fatal: the full path below is always
            // able to produce the same bytes, just more slowly.
            if let Some(base) = payload::load(app, running_version()) {
                emit_state(
                    app,
                    &state_payload(
                        "downloading",
                        Some(version.clone()),
                        Some(0.0),
                        Some(0),
                        None,
                        None,
                        Some(Mode::Delta),
                    ),
                );
                let attempted = payload::fetch_delta(
                    &update.download_url.to_string(),
                    running_version(),
                    &version,
                    &base,
                )
                .await;
                match attempted {
                    Ok(artifact) => {
                        log::info!("delta update to {version} rebuilt from the cached payload");
                        // Cache the result so the next update can delta again.
                        payload::store(app, &artifact.version, &artifact.bytes);
                        stage_pending(&version, artifact.bytes, Mode::Delta);
                        let s = state_payload(
                            "ready",
                            Some(version),
                            Some(100.0),
                            None,
                            None,
                            None,
                            Some(Mode::Delta),
                        );
                        emit_state(app, &s);
                        return s;
                    }
                    Err(e) => log::warn!("delta update unavailable ({e}); using the full update"),
                }
            }

            // --- Full update (fallback) --------------------------------------
            emit_state(
                app,
                &state_payload(
                    "downloading",
                    Some(version.clone()),
                    Some(0.0),
                    Some(0),
                    None,
                    None,
                    Some(Mode::Full),
                ),
            );
            let mut downloaded: u64 = 0;
            let app2 = app.clone();
            let version2 = version.clone();
            let res = update
                .download(
                    move |chunk, total| {
                        downloaded = downloaded.saturating_add(chunk as u64);
                        let pct = total
                            .map(|t| (downloaded as f64 / t as f64) * 100.0)
                            .unwrap_or(0.0);
                        emit_state(
                            &app2,
                            &state_payload(
                                "downloading",
                                Some(version2.clone()),
                                Some(pct.min(100.0)),
                                Some(downloaded),
                                total,
                                None,
                                Some(Mode::Full),
                            ),
                        );
                    },
                    || {},
                )
                .await;
            match res {
                Ok(bytes) => {
                    // The plugin verified the minisign signature before handing
                    // these bytes over, so caching them as a future delta base is
                    // safe.
                    payload::store(app, &version, &bytes);
                    // Stage the verified artifact so install_update() can apply
                    // it without a second download.
                    stage_pending(&version, bytes, Mode::Full);
                    let s = state_payload(
                        "ready",
                        Some(version),
                        Some(100.0),
                        None,
                        None,
                        None,
                        Some(Mode::Full),
                    );
                    emit_state(app, &s);
                    s
                }
                Err(e) => {
                    let s = state_payload("error", None, None, None, None, Some(e.to_string()), None);
                    emit_state(app, &s);
                    s
                }
            }
        }
        Ok(None) => {
            let s = state_payload("up-to-date", None, None, None, None, None, None);
            emit_state(app, &s);
            s
        }
        Err(e) => {
            let s = state_payload("error", None, None, None, None, Some(e.to_string()), None);
            emit_state(app, &s);
            s
        }
    }
}

#[derive(Clone)]
struct PendingUpdate {
    version: String,
    bytes: Vec<u8>,
    mode: Mode,
    /// SHA-256 of `bytes`, taken the moment the download was verified. The
    /// artifact is re-hashed immediately before it is handed to the installer,
    /// so anything that touches the bytes in between is caught rather than
    /// executed.
    digest: [u8; 32],
}

static PENDING: Mutex<Option<PendingUpdate>> = Mutex::new(None);

/// Set while a check/download is running. The 5-minute tick, the startup
/// check and a manual "Check now" from Settings can otherwise overlap and
/// start two downloads of the same release.
///
/// An atomic rather than a `Mutex<bool>`: holding a `MutexGuard` across an
/// await makes the whole command future non-`Send`, which Tauri rejects.
static IN_FLIGHT: AtomicBool = AtomicBool::new(false);

/// Claims the single check slot. False means a check is already running.
fn claim_check_slot() -> bool {
    IN_FLIGHT
        .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
        .is_ok()
}

fn release_check_slot() {
    IN_FLIGHT.store(false, Ordering::Release);
}

/// Epoch ms before which no new check is attempted, set after a failure so an
/// offline machine retries on a backoff instead of every five minutes forever.
static BACKOFF_UNTIL_MS: Mutex<u64> = Mutex::new(0);

/// Consecutive failures, used to widen the backoff. Capped.
static FAILURE_STREAK: Mutex<u32> = Mutex::new(0);

/// True once an install has been handed to the installer. Nothing may start
/// another update afterwards: the app is on its way down, and a second check
/// landing in that window is how update loops happen.
static INSTALL_STARTED: Mutex<bool> = Mutex::new(false);

/// How long the user must have been idle before an update is applied without
/// being asked. Deliberately long: restarting someone's machine while they
/// are mid-thought is worse than restarting it five minutes later.
const IDLE_APPLY_MS: u64 = 10 * 60_000;

/// First backoff after a failure, doubled per consecutive failure, capped.
const BACKOFF_BASE_MS: u64 = 5 * 60_000;
const BACKOFF_MAX_MS: u64 = 60 * 60_000;

fn backoff_until_ms() -> u64 {
    *BACKOFF_UNTIL_MS.lock().unwrap_or_else(|e| e.into_inner())
}

fn note_failure() {
    let mut streak = FAILURE_STREAK.lock().unwrap_or_else(|e| e.into_inner());
    *streak += 1;
    let shift = (*streak).saturating_sub(1).min(4);
    let wait = BACKOFF_BASE_MS.saturating_mul(1u64 << shift).min(BACKOFF_MAX_MS);
    *BACKOFF_UNTIL_MS.lock().unwrap_or_else(|e| e.into_inner()) = crate::util::now_ms() + wait;
    log::warn!("[1boost] update check failed; next attempt in {wait / 1000}s");
}

fn note_success() {
    *FAILURE_STREAK.lock().unwrap_or_else(|e| e.into_inner()) = 0;
    *BACKOFF_UNTIL_MS.lock().unwrap_or_else(|e| e.into_inner()) = 0;
}

fn install_started() -> bool {
    *INSTALL_STARTED.lock().unwrap_or_else(|e| e.into_inner())
}

/// Re-hashes the staged artifact and confirms it is still the bytes we
/// verified at download time.
fn pending_is_intact(p: &PendingUpdate) -> bool {
    crate::delta::sha256(&p.bytes) == p.digest
}

/// Replaces the staged update. Returns false when the new artifact is for a
/// version we already staged, which keeps repeated checks from re-downloading
/// (and re-verifying) an update the user has simply not restarted yet.
fn stage_pending(version: &str, bytes: Vec<u8>, mode: Mode) -> bool {
    let mut guard = PENDING.lock().unwrap_or_else(|e| e.into_inner());
    if let Some(existing) = guard.as_ref() {
        if existing.version == version {
            return false;
        }
    }
    *guard = Some(PendingUpdate {
        version: version.to_string(),
        digest: crate::delta::sha256(&bytes),
        bytes,
        mode,
    });
    true
}

fn pending_version() -> Option<String> {
    PENDING.lock().unwrap_or_else(|e| e.into_inner()).as_ref().map(|p| p.version.clone())
}

/// The state the UI asks for on load.
///
/// A staged update outlives the page that was open when it downloaded, so
/// this has to report the truth rather than a fixed "idle": opening Settings
/// minutes later must still say an update is ready, or the user is told to
/// wait for something that has already finished.
pub async fn update_state(_app: &AppHandle) -> UpdateStatePayload {
    let guard = PENDING.lock().unwrap_or_else(|e| e.into_inner());
    match guard.as_ref() {
        Some(p) => {
            let intact = pending_is_intact(p);
            state_payload(
                if intact { "ready" } else { "error" },
                Some(p.version.clone()),
                if intact { Some(100.0) } else { None },
                None,
                None,
                if intact { None } else { Some("the downloaded update no longer matches what was verified".into()) },
                Some(p.mode),
            )
        }
        None => state_payload("idle", None, None, None, None, None, None),
    }
}

/// True when a release manifest version is newer than the running build.
#[allow(dead_code)]
fn is_newer(candidate: &str, current: &str) -> bool {
    payload::is_newer(candidate, current)
}

pub async fn check_updates(app: &AppHandle) -> UpdateStatePayload {
    // A manual "Check now" from Settings must not race the background tick.
    if !claim_check_slot() {
        return state_payload("checking", None, None, None, None, None, None);
    }
    let result = do_check(app).await;
    release_check_slot();
    result
}

/// Applies a staged update, re-verifying the artifact on the way in.
///
/// Verification happens twice on purpose. The signature is checked when the
/// bytes are downloaded (by the plugin, or by the delta chain), and then the
/// artifact is re-hashed here against the digest recorded at that moment. A
/// truncated cache write, a half-flushed file or anything else that touches
/// the staged bytes between download and install is caught before the
/// installer ever sees them.
pub async fn install_update(app: &AppHandle) -> bool {
    if install_started() {
        return false;
    }
    let updater = match app.updater() {
        Ok(u) => u,
        Err(_) => return false,
    };
    // Check again so the Update object matches the live feed.
    let update = match updater.check().await {
        Ok(Some(u)) => u,
        _ => return false,
    };

    let staged = PENDING.lock().unwrap_or_else(|e| e.into_inner()).clone();
    let bytes = match staged {
        Some(p) if p.version == update.version => {
            if !pending_is_intact(&p) {
                log::error!("[1boost] staged update {} failed its integrity check", p.version);
                // Drop it rather than leaving a corrupt artifact to be retried.
                *PENDING.lock().unwrap_or_else(|e| e.into_inner()) = None;
                return false;
            }
            // A verified updater artifact is a zip containing the installer.
            if extract_installer(&p.bytes).is_none() {
                log::error!("[1boost] staged update {} is not an installer archive", p.version);
                *PENDING.lock().unwrap_or_else(|e| e.into_inner()) = None;
                return false;
            }
            Ok(p.bytes)
        }
        // Background download never completed — fetch now. The plugin
        // verifies this one's signature on the way in.
        _ => update.download(|_, _| {}, || {}).await,
    };

    let bytes = match bytes {
        Ok(b) => b,
        Err(e) => {
            log::warn!("[1boost] could not fetch the update to install: {e}");
            return false;
        }
    };

    // From here the app is committed to restarting. Mark it before handing
    // control to the installer so a concurrent timer tick cannot start a
    // second update on the way out.
    *INSTALL_STARTED.lock().unwrap_or_else(|e| e.into_inner()) = true;
    // install() replaces the binary and relaunches (NSIS).
    match update.install(&bytes) {
        Ok(()) => true,
        Err(e) => {
            // The installer refused. Let the app carry on and try again later
            // rather than exiting into a half-applied state.
            log::error!("[1boost] the installer refused the update: {e}");
            *INSTALL_STARTED.lock().unwrap_or_else(|e| e.into_inner()) = false;
            false
        }
    }
}

/// Applies a staged update without being asked, once the machine has been
/// idle long enough that restarting cannot interrupt anyone.
///
/// Returns true when an install was started.
pub async fn auto_apply_if_idle(app: &AppHandle) -> bool {
    if install_started() {
        return false;
    }
    // The tracker lives inside AppState as an Arc, not as a directly managed
    // state type.
    let idle = app.state::<crate::AppState>().tracker.idle_ms();
    // Never apply before the user has had a fair chance to see the prompt,
    // and never while the window is in front of them.
    let Some(idle) = idle else { return false };
    if idle < IDLE_APPLY_MS {
        return false;
    }
    let window_in_front = app
        .get_webview_window("main")
        .and_then(|w| w.is_visible().ok())
        .unwrap_or(false)
        && app
            .get_webview_window("main")
            .and_then(|w| w.is_focused().ok())
            .unwrap_or(false);
    if window_in_front {
        return false;
    }
    let Some(version) = pending_version() else { return false };
    log::info!("[1boost] idle for {}ms; applying the staged update to {version}", idle);
    install_update(app).await
}

/// Reinstalls the newest cached payload older than the running build.
///
/// The candidate is the artifact 1Boost itself downloaded and hash-verified
/// earlier, so this does not widen the trust boundary; it is the recovery path
/// for an update that installed but misbehaved.
pub async fn rollback_update(app: AppHandle) -> Result<Option<String>, String> {
    let current = running_version();
    let Some((version, bytes)) = payload::rollback_candidate(&app, current) else {
        return Ok(None);
    };

    let installer = extract_installer(&bytes).ok_or_else(|| {
        format!("the cached payload for {version} is not a usable installer archive")
    })?;

    // Stage the installer in the temp directory rather than next to the payload
    // cache: a rollback is rare, and a multi-megabyte executable left behind in
    // the app's data folder every time would never be cleaned up.
    let staged = std::env::temp_dir().join(format!("1boost-rollback-{version}.exe"));
    let mut file = std::fs::File::create(&staged).map_err(|e| e.to_string())?;
    file.write_all(&installer).map_err(|e| e.to_string())?;
    drop(file);

    std::process::Command::new(&staged)
        .arg("/S")
        .spawn()
        .map_err(|e| e.to_string())?;
    app.exit(0);
    Ok(Some(version))
}

/// Pulls the installer executable out of a cached NSIS updater payload.
fn extract_installer(bytes: &[u8]) -> Option<Vec<u8>> {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).ok()?;
    for index in 0..archive.len() {
        let mut entry = archive.by_index(index).ok()?;
        let is_installer = entry
            .name()
            .rsplit('/')
            .next()
            .is_some_and(|name| name.to_ascii_lowercase().ends_with(".exe"));
        if !is_installer {
            continue;
        }
        let mut out = Vec::with_capacity(entry.size() as usize);
        entry.read_to_end(&mut out).ok()?;
        return Some(out);
    }
    None
}

/// The background updater loop.
///
/// One thread, one job at a time. Every tick either checks for a release (if
/// no failure backoff is active) or, if an update is already staged, decides
/// whether the machine has been idle long enough to restart on its own.
pub fn init_background(app: AppHandle) {
    if cfg!(debug_assertions) || std::env::var("ONEBOOST_NO_UPDATER").as_deref() == Ok("1") {
        return;
    }
    std::thread::spawn(move || {
        // Small delay so first paint isn't competing with the update check.
        std::thread::sleep(std::time::Duration::from_millis(STARTUP_DELAY_MS));
        loop {
            let now = crate::util::now_ms();
            let due = now >= backoff_until_ms();
            if due && !install_started() && claim_check_slot() {
                let h = app.clone();
                tauri::async_runtime::spawn(async move {
                    let state = do_check(&h).await;
                    // Every terminal outcome resets the backoff, so a
                    // recovered network is picked up on the next tick.
                    if state.status == "error" {
                        note_failure();
                    } else {
                        note_success();
                    }
                    release_check_slot();
                });
            } else if !due {
                log::debug!(
                    "[1boost] update check backing off for another {}s",
                    (backoff_until_ms().saturating_sub(now)) / 1000
                );
            }

            // A staged update waits for the user — until they are idle.
            let staged = pending_version();
            if staged.is_some() {
                let h = app.clone();
                tauri::async_runtime::spawn(async move {
                    auto_apply_if_idle(&h).await;
                });
            }

            std::thread::sleep(std::time::Duration::from_millis(RECHECK_MS));
        }
    });
}

const STARTUP_DELAY_MS: u64 = 15_000;

/// How often the updater looks for a new release. Five minutes is frequent
/// enough that an update lands while the app is still open, and cheap enough
/// (a signed manifest fetch) that it is not worth being cleverer.
const RECHECK_MS: u64 = 5 * 60_000;

// Repo constants kept for the manifest generator + diagnostics.
pub const REPO: (&str, &str) = (REPO_OWNER, REPO_NAME);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::delta;

    #[test]
    fn reuses_the_payload_version_comparison() {
        assert!(is_newer("1.3.2", "1.3.1"));
        assert!(!is_newer("1.3.1", "1.3.1"));
    }

    #[test]
    fn reports_the_mode_it_installed_from() {
        assert_eq!(Mode::Delta.as_str(), "delta");
        assert_eq!(Mode::Full.as_str(), "full");
    }

    #[test]
    fn builds_the_delta_url_next_to_the_full_payload() {
        // The patch must be fetched from the release the signed manifest named,
        // so the URL is derived from the payload's own URL.
        let payload_url = "https://github.com/Ahaduzzamankhan/1boost/releases/download/v1.3.2/1Boost_1.3.2_x64-setup.nsis.zip";
        let (dir, _) = payload_url.rsplit_once('/').unwrap();
        let url = format!("{dir}/{}", payload::delta_asset_name("1.3.1", "1.3.2"));
        assert_eq!(
            url,
            "https://github.com/Ahaduzzamankhan/1boost/releases/download/v1.3.2/1Boost_1.3.2_x64-setup.from-1.3.1.1bdelta"
        );
    }

    #[test]
    fn refuses_a_payload_that_is_not_an_installer_archive() {
        assert!(extract_installer(b"not a zip file").is_none());
        assert!(extract_installer(&[]).is_none());
    }

    #[test]
    fn round_trips_the_fixture_through_the_public_delta_api() {
        // Guards the wiring the updater uses, not just the format.
        let base = include_bytes!("delta_fixtures/base.bin");
        let target = include_bytes!("delta_fixtures/target.bin");
        let patch = include_bytes!("delta_fixtures/patch.1bdelta");
        assert_eq!(delta::rebuild(patch, base).unwrap(), target);
    }

    /// These tests share the process-wide PENDING slot, so they take a lock of
    /// their own rather than running against each other.
    static TEST_LOCK: Mutex<()> = Mutex::new(());

    fn with_pending<T>(f: impl FnOnce() -> T) -> T {
        let _guard = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let result = f();
        *PENDING.lock().unwrap_or_else(|e| e.into_inner()) = None;
        *INSTALL_STARTED.lock().unwrap_or_else(|e| e.into_inner()) = false;
        result
    }

    #[test]
    fn staging_the_same_version_twice_does_not_redownload() {
        with_pending(|| {
            assert!(stage_pending("1.3.2", vec![1, 2, 3], Mode::Full));
            // A second check five minutes later must not fetch the same bytes.
            assert!(!stage_pending("1.3.2", vec![9, 9, 9], Mode::Full));
            assert_eq!(pending_version().as_deref(), Some("1.3.2"));
            // A genuinely newer release does replace it.
            assert!(stage_pending("1.3.3", vec![4, 5, 6], Mode::Delta));
            assert_eq!(pending_version().as_deref(), Some("1.3.3"));
        });
    }

    #[test]
    fn a_staged_update_that_changes_is_caught_before_installing() {
        with_pending(|| {
            stage_pending("1.3.2", vec![1, 2, 3, 4], Mode::Full);
            let staged = PENDING.lock().unwrap_or_else(|e| e.into_inner()).clone().unwrap();
            assert!(pending_is_intact(&staged));
            // Anything that touches the staged bytes after verification fails.
            let mut tampered = staged.clone();
            tampered.bytes[0] ^= 0xff;
            assert!(!pending_is_intact(&tampered));
            let mut truncated = staged.clone();
            truncated.bytes.pop();
            assert!(!pending_is_intact(&truncated));
        });
    }

    #[test]
    fn backoff_widens_then_resets() {
        let _guard = TEST_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        *FAILURE_STREAK.lock().unwrap_or_else(|e| e.into_inner()) = 0;
        *BACKOFF_UNTIL_MS.lock().unwrap_or_else(|e| e.into_inner()) = 0;
        assert_eq!(backoff_until_ms(), 0, "a healthy machine starts with no wait");

        note_failure();
        let first = backoff_until_ms().saturating_sub(crate::util::now_ms());
        assert!(first > 0 && first <= BACKOFF_MAX_MS);

        note_failure();
        let second = backoff_until_ms().saturating_sub(crate::util::now_ms());
        assert!(second >= first, "repeated failures wait longer than the first");

        for _ in 0..10 {
            note_failure();
        }
        assert!(
            backoff_until_ms().saturating_sub(crate::util::now_ms()) <= BACKOFF_MAX_MS,
            "the backoff is capped so an outage cannot park the updater forever"
        );

        note_success();
        assert_eq!(backoff_until_ms(), 0);
        *FAILURE_STREAK.lock().unwrap_or_else(|e| e.into_inner()) = 0;
    }

    #[test]
    fn the_idle_threshold_is_long_enough_to_be_safe() {
        // Restarting while someone is typing is the failure this guards.
        assert!(IDLE_APPLY_MS >= 5 * 60_000, "wait at least five idle minutes");
    }
}