//! Auto-update for 1Boost.
//!
//! Two paths, in order of preference:
//!
//!   1. **Delta** — releases publish a signed `.1bdelta` patch next to the
//!      signed updater payload (see `delta` and `payload`). When the payload of
//!      the running version is in the cache, the new one is rebuilt locally and
//!      only a few kilobytes cross the network.
//!   2. **Full** — the tauri-plugin-updater path, unchanged. It is used
//!      whenever there is no cached base, no published patch, or the patch
//!      fails any verification step. This is also the only path on a fresh
//!      install, which has no payload on disk to patch against.
//!
//! Nothing about the full-update path was weakened: the plugin still verifies
//! the artifact's minisign signature itself, and the delta path adds the same
//! check plus a SHA-256 chain on top (see `delta`). Updates are staged in
//! memory and only handed to the installer once verified, so a failed update of
//! either kind leaves the current install untouched.
//!
//! Release feed: every stable tag publishes `latest.json` generated by CI
//! (scripts/gen-latest-json.mjs) pointing at the NSIS `*.exe` artifact, with a
//! minisign signature produced at build time (TAURI_SIGNING_PRIVATE_KEY).

use crate::payload;
use serde::Serialize;
use std::io::Read;
use std::io::Write;
use std::sync::Mutex;
use tauri::AppHandle;
use tauri_plugin_updater::UpdaterExt;

const REPO_OWNER: &str = "Ahaduzzamankhan";
const REPO_NAME: &str = "1boost";

/// Which path produced the bytes now waiting to be installed.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Mode {
    Delta,
    Full,
}

impl Mode {
    fn as_str(self) -> &'static str {
        match self {
            Mode::Delta => "delta",
            Mode::Full => "full",
        }
    }
}

#[derive(Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UpdateStatePayload {
    pub status: String,
    pub current_version: String,
    pub available_version: Option<String>,
    pub progress: Option<f64>,
    pub downloaded_bytes: Option<u64>,
    pub total_bytes: Option<u64>,
    pub error: Option<String>,
    pub checked_at: Option<u64>,
    /// "delta" or "full": which updater path produced this update.
    pub mode: Option<String>,
}

#[allow(clippy::too_many_arguments)]
fn state_payload(
    status: &str,
    available: Option<String>,
    progress: Option<f64>,
    downloaded: Option<u64>,
    total: Option<u64>,
    error: Option<String>,
    mode: Option<Mode>,
) -> UpdateStatePayload {
    UpdateStatePayload {
        status: status.to_string(),
        current_version: env!("CARGO_PKG_VERSION").to_string(),
        available_version: available,
        progress,
        downloaded_bytes: downloaded,
        total_bytes: total,
        error,
        checked_at: Some(crate::util::now_ms()),
        mode: mode.map(Mode::as_str).map(str::to_string),
    }
}

fn running_version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

#[allow(dead_code)]
fn running_prerelease() -> bool {
    let v = running_version();
    v.contains("-alpha") || v.contains("-beta")
}

fn emit_state(app: &AppHandle, s: &UpdateStatePayload) {
    use tauri::Emitter;
    let _ = app.emit("oneboost://update-state", s);
}

async fn do_check(app: &AppHandle) -> UpdateStatePayload {
    if std::env::var("ONEBOOST_NO_UPDATER").as_deref() == Ok("1") {
        return state_payload("up-to-date", None, None, None, None, None, None);
    }
    let updater = match app.updater() {
        Ok(u) => u,
        Err(e) => {
            return state_payload("error", None, None, None, None, Some(e.to_string()), None)
        }
    };
    emit_state(app, &state_payload("checking", None, None, None, None, None, None));
    match updater.check().await {
        Ok(Some(update)) => {
            let version = update.version.clone();

            // --- Delta first -------------------------------------------------
            // Every failure below is non-fatal: the full path below is always
            // able to produce the same bytes, just more slowly.
            if let Some(base) = payload::load(app, running_version()) {
                emit_state(
                    app,
                    &state_payload(
                        "downloading",
                        Some(version.clone()),
                        Some(0.0),
                        Some(0),
                        None,
                        None,
                        Some(Mode::Delta),
                    ),
                );
                let attempted = payload::fetch_delta(
                    &update.download_url.to_string(),
                    running_version(),
                    &version,
                    &base,
                )
                .await;
                match attempted {
                    Ok(artifact) => {
                        log::info!("delta update to {version} rebuilt from the cached payload");
                        // Cache the result so the next update can delta again.
                        payload::store(app, &artifact.version, &artifact.bytes);
                        if let Ok(mut g) = PENDING.lock() {
                            *g = Some(PendingUpdate {
                                version: version.clone(),
                                bytes: artifact.bytes,
                                mode: Mode::Delta,
                            });
                        }
                        let s = state_payload(
                            "ready",
                            Some(version),
                            Some(100.0),
                            None,
                            None,
                            None,
                            Some(Mode::Delta),
                        );
                        emit_state(app, &s);
                        return s;
                    }
                    Err(e) => log::warn!("delta update unavailable ({e}); using the full update"),
                }
            }

            // --- Full update (fallback) --------------------------------------
            emit_state(
                app,
                &state_payload(
                    "downloading",
                    Some(version.clone()),
                    Some(0.0),
                    Some(0),
                    None,
                    None,
                    Some(Mode::Full),
                ),
            );
            let mut downloaded: u64 = 0;
            let app2 = app.clone();
            let version2 = version.clone();
            let res = update
                .download(
                    move |chunk, total| {
                        downloaded = downloaded.saturating_add(chunk as u64);
                        let pct = total
                            .map(|t| (downloaded as f64 / t as f64) * 100.0)
                            .unwrap_or(0.0);
                        emit_state(
                            &app2,
                            &state_payload(
                                "downloading",
                                Some(version2.clone()),
                                Some(pct.min(100.0)),
                                Some(downloaded),
                                total,
                                None,
                                Some(Mode::Full),
                            ),
                        );
                    },
                    || {},
                )
                .await;
            match res {
                Ok(bytes) => {
                    // The plugin verified the minisign signature before handing
                    // these bytes over, so caching them as a future delta base is
                    // safe.
                    payload::store(app, &version, &bytes);
                    // Cache the downloaded artifact so install_update() can
                    // install it without a second download.
                    if let Ok(mut g) = PENDING.lock() {
                        *g = Some(PendingUpdate {
                            version: version.clone(),
                            bytes,
                            mode: Mode::Full,
                        });
                    }
                    let s = state_payload(
                        "ready",
                        Some(version),
                        Some(100.0),
                        None,
                        None,
                        None,
                        Some(Mode::Full),
                    );
                    emit_state(app, &s);
                    s
                }
                Err(e) => {
                    let s = state_payload("error", None, None, None, None, Some(e.to_string()), None);
                    emit_state(app, &s);
                    s
                }
            }
        }
        Ok(None) => {
            let s = state_payload("up-to-date", None, None, None, None, None, None);
            emit_state(app, &s);
            s
        }
        Err(e) => {
            let s = state_payload("error", None, None, None, None, Some(e.to_string()), None);
            emit_state(app, &s);
            s
        }
    }
}

#[derive(Clone)]
struct PendingUpdate {
    version: String,
    bytes: Vec<u8>,
    mode: Mode,
}

static PENDING: Mutex<Option<PendingUpdate>> = Mutex::new(None);

pub async fn update_state(_app: &AppHandle) -> UpdateStatePayload {
    // Non-mutating snapshot: the UI polls this on load.
    state_payload("idle", None, None, None, None, None, None)
}

/// True when a release manifest version is newer than the running build.
#[allow(dead_code)]
fn is_newer(candidate: &str, current: &str) -> bool {
    payload::is_newer(candidate, current)
}

pub async fn check_updates(app: &AppHandle) -> UpdateStatePayload {
    do_check(app).await
}

pub async fn install_update(app: &AppHandle) -> bool {
    let updater = match app.updater() {
        Ok(u) => u,
        Err(_) => return false,
    };
    // Check again so the Update object matches the live feed.
    match updater.check().await {
        Ok(Some(update)) => {
            let pending = PENDING.lock().ok().and_then(|g| g.clone());
            let bytes = match pending {
                Some(p) if p.version == update.version => Ok(p.bytes),
                // Background download never completed — fetch now. The plugin
                // verifies this one's signature on the way in.
                _ => update.download(|_, _| {}, || {}).await,
            };
            match bytes {
                // install() replaces the binary and relaunches (NSIS);
                // ExitRequested stops the tracker via RunEvent handling.
                Ok(b) => {
                    let _ = update.install(&b);
                    true
                }
                Err(_) => false,
            }
        }
        _ => false,
    }
}

/// Reinstalls the newest cached payload older than the running build.
///
/// The candidate is the artifact 1Boost itself downloaded and hash-verified
/// earlier, so this does not widen the trust boundary; it is the recovery path
/// for an update that installed but misbehaved.
pub async fn rollback_update(app: AppHandle) -> Result<Option<String>, String> {
    let current = running_version();
    let Some((version, bytes)) = payload::rollback_candidate(&app, current) else {
        return Ok(None);
    };

    let installer = extract_installer(&bytes).ok_or_else(|| {
        format!("the cached payload for {version} is not a usable installer archive")
    })?;

    // Stage the installer in the temp directory rather than next to the payload
    // cache: a rollback is rare, and a multi-megabyte executable left behind in
    // the app's data folder every time would never be cleaned up.
    let staged = std::env::temp_dir().join(format!("1boost-rollback-{version}.exe"));
    let mut file = std::fs::File::create(&staged).map_err(|e| e.to_string())?;
    file.write_all(&installer).map_err(|e| e.to_string())?;
    drop(file);

    std::process::Command::new(&staged)
        .arg("/S")
        .spawn()
        .map_err(|e| e.to_string())?;
    app.exit(0);
    Ok(Some(version))
}

/// Pulls the installer executable out of a cached NSIS updater payload.
fn extract_installer(bytes: &[u8]) -> Option<Vec<u8>> {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(bytes)).ok()?;
    for index in 0..archive.len() {
        let mut entry = archive.by_index(index).ok()?;
        let is_installer = entry
            .name()
            .rsplit('/')
            .next()
            .is_some_and(|name| name.to_ascii_lowercase().ends_with(".exe"));
        if !is_installer {
            continue;
        }
        let mut out = Vec::with_capacity(entry.size() as usize);
        entry.read_to_end(&mut out).ok()?;
        return Some(out);
    }
    None
}

pub fn init_background(app: AppHandle) {
    if cfg!(debug_assertions) || std::env::var("ONEBOOST_NO_UPDATER").as_deref() == Ok("1") {
        return;
    }
    std::thread::spawn(move || {
        // Small delay so first paint isn't competing with the update check.
        std::thread::sleep(std::time::Duration::from_millis(STARTUP_DELAY_MS));
        let h = app.clone();
        tauri::async_runtime::spawn(async move {
            do_check(&h).await;
        });
        loop {
            std::thread::sleep(std::time::Duration::from_millis(RECHECK_MS));
            let h = app.clone();
            tauri::async_runtime::spawn(async move {
                do_check(&h).await;
            });
        }
    });
}

const STARTUP_DELAY_MS: u64 = 15_000;
const RECHECK_MS: u64 = 6 * 60 * 60_000;

// Repo constants kept for the manifest generator + diagnostics.
pub const REPO: (&str, &str) = (REPO_OWNER, REPO_NAME);

#[cfg(test)]
mod tests {
    use super::*;
    use crate::delta;

    #[test]
    fn reuses_the_payload_version_comparison() {
        assert!(is_newer("1.3.2", "1.3.1"));
        assert!(!is_newer("1.3.1", "1.3.1"));
    }

    #[test]
    fn reports_the_mode_it_installed_from() {
        assert_eq!(Mode::Delta.as_str(), "delta");
        assert_eq!(Mode::Full.as_str(), "full");
    }

    #[test]
    fn builds_the_delta_url_next_to_the_full_payload() {
        // The patch must be fetched from the release the signed manifest named,
        // so the URL is derived from the payload's own URL.
        let payload_url = "https://github.com/Ahaduzzamankhan/1boost/releases/download/v1.3.2/1Boost_1.3.2_x64-setup.nsis.zip";
        let (dir, _) = payload_url.rsplit_once('/').unwrap();
        let url = format!("{dir}/{}", payload::delta_asset_name("1.3.1", "1.3.2"));
        assert_eq!(
            url,
            "https://github.com/Ahaduzzamankhan/1boost/releases/download/v1.3.2/1Boost_1.3.2_x64-setup.from-1.3.1.1bdelta"
        );
    }

    #[test]
    fn refuses_a_payload_that_is_not_an_installer_archive() {
        assert!(extract_installer(b"not a zip file").is_none());
        assert!(extract_installer(&[]).is_none());
    }

    #[test]
    fn round_trips_the_fixture_through_the_public_delta_api() {
        // Guards the wiring the updater uses, not just the format.
        let base = include_bytes!("delta_fixtures/base.bin");
        let target = include_bytes!("delta_fixtures/target.bin");
        let patch = include_bytes!("delta_fixtures/patch.1bdelta");
        assert_eq!(delta::rebuild(patch, base).unwrap(), target);
    }
}